-- schema.sql

-- Drop existing tables if they exist (for development/testing purposes)
DROP TABLE IF EXISTS adaptations;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS users;

-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    bio TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create recipes table
CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    cooking_time INTEGER,
    servings INTEGER,
    category VARCHAR(255),
    image_url VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create ratings table
CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    rating_value INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, recipe_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

-- Create reviews table
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

-- Create adaptations table
CREATE TABLE adaptations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    suggestion TEXT NOT NULL,
    upvotes INTEGER DEFAULT 0,
    downvotes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

-- Insert initial data for users
INSERT INTO users (username, password, display_name, bio) VALUES
('user1', '$2a$10$examplehashedpassword1', 'User One', 'Loves to cook Italian food.'),
('foodiegal', '$2a$10$anotherhashedpassword', 'Foodie Gal', 'Exploring cuisines from around the world.'),
('masterchef', '$2a$10$yetanotherhash', 'Master Chef', 'Passionate about baking and pastry.');

-- Insert initial data for recipes
INSERT INTO recipes (user_id, title, ingredients, instructions, cooking_time, servings, category, image_url) VALUES
((SELECT id FROM users WHERE username = 'user1'), 'Spaghetti Carbonara', 'Spaghetti, Eggs, Guanciale, Pecorino Romano, Black Pepper', 'Cook spaghetti. Sauté guanciale. Whisk eggs and cheese. Combine everything.', 20, 2, 'Italian', 'https://example.com/carbonara.jpg'),
((SELECT id FROM users WHERE username = 'foodiegal'), 'Chicken Stir-Fry', 'Chicken, Broccoli, Carrots, Soy Sauce, Ginger, Garlic, Rice', 'Stir-fry chicken and vegetables. Add sauce. Serve with rice.', 30, 4, 'Asian', 'https://example.com/stirfry.jpg'),
((SELECT id FROM users WHERE username = 'masterchef'), 'Chocolate Cake', 'Flour, Sugar, Cocoa Powder, Eggs, Butter, Milk', 'Mix ingredients. Bake in oven. Frost when cooled.', 60, 8, 'Dessert', 'https://example.com/chocolatecake.jpg');

-- Insert initial data for ratings
INSERT INTO ratings (user_id, recipe_id, rating_value) VALUES
((SELECT id FROM users WHERE username = 'foodiegal'), (SELECT id FROM recipes WHERE title = 'Spaghetti Carbonara'), 4),
((SELECT id FROM users WHERE username = 'masterchef'), (SELECT id FROM recipes WHERE title = 'Spaghetti Carbonara'), 5),
((SELECT id FROM users WHERE username = 'user1'), (SELECT id FROM recipes WHERE title = 'Chicken Stir-Fry'), 3),
((SELECT id FROM users WHERE username = 'masterchef'), (SELECT id FROM recipes WHERE title = 'Chicken Stir-Fry'), 4),
((SELECT id FROM users WHERE username = 'user1'), (SELECT id FROM recipes WHERE title = 'Chocolate Cake'), 5),
((SELECT id FROM users WHERE username = 'foodiegal'), (SELECT id FROM recipes WHERE title = 'Chocolate Cake'), 4);

-- Insert initial data for reviews
INSERT INTO reviews (user_id, recipe_id, comment) VALUES
((SELECT id FROM users WHERE username = 'foodiegal'), (SELECT id FROM recipes WHERE title = 'Spaghetti Carbonara'), 'Authentic and delicious!'),
((SELECT id FROM users WHERE username = 'masterchef'), (SELECT id FROM recipes WHERE title = 'Spaghetti Carbonara'), 'Simple but perfect.'),
((SELECT id FROM users WHERE username = 'user1'), (SELECT id FROM recipes WHERE title = 'Chicken Stir-Fry'), 'A quick and easy weeknight meal.'),
((SELECT id FROM users WHERE username = 'masterchef'), (SELECT id FROM recipes WHERE title = 'Chicken Stir-Fry'), 'Could use a bit more spice.'),
((SELECT id FROM users WHERE username = 'user1'), (SELECT id FROM recipes WHERE title = 'Chocolate Cake'), 'Moist and rich!'),
((SELECT id FROM users WHERE username = 'foodiegal'), (SELECT id FROM recipes WHERE title = 'Chocolate Cake'), 'Great for birthdays.');

-- Insert initial data for adaptations
INSERT INTO adaptations (user_id, recipe_id, suggestion) VALUES
((SELECT id FROM users WHERE username = 'foodiegal'), (SELECT id FROM recipes WHERE title = 'Spaghetti Carbonara'), 'Try adding a splash of white wine while cooking the guanciale.'),
((SELECT id FROM users WHERE username = 'user1'), (SELECT id FROM recipes WHERE title = 'Chicken Stir-Fry'), 'Substitute tofu for a vegetarian option.'),
((SELECT id FROM users WHERE username = 'masterchef'), (SELECT id FROM recipes WHERE title = 'Chocolate Cake'), 'A pinch of espresso powder enhances the chocolate flavor.');